### ISSUE TITLE
Support for Float type

### ISSUE THREAD

**Issue by apexskier** [mattt/Surge#11]
I'd like to discuss adding support for the Float type to Surge. I've done this in [apexskier/Surge on the float branch](https://github.com/apexskier/Surge/compare/float).

I was planning on using this to integrate Accelerate with SceneKit through Surge and a [library](https://github.com/apexskier/SKLinearAlgebra) I'm writing. I've since found that it's [only necessary on 32 bit platforms](https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/Cocoa64BitGuide/64BitChangesCocoa/64BitChangesCocoa.html#//apple_ref/doc/uid/TP40004247-CH4-SW9#//apple_ref/doc/uid/TP40004247-CH4-SW13), so I can see an argument against the extra code.

Any opinions?

**Comment by apexskier** [comment]
I misspoke, looks like SceneKit is using Float, not CGFloat.

**Comment by mattt** [comment]
3363779d666c0581a4103f004dc136479fa09aab and c1bad0a0244ed04de7a11692b669f78f709cff0b add support for overloaded functions using Float. This is now live in version 0.2.0.

**Comment by apexskier** [comment]
Awesome!
