### ISSUE TITLE
Memory leak of the fft function / fft関数のメモリリーク

### ISSUE THREAD

**Issue by kiha-la** [mattt/Surge#12]
I use fft function for the real-time pitch detection , but troubled with the its memory consumption.
I perform fft about 60 times every one second, but memory is used at every function practice by number KB, as a result  number GB is used immediately.

I write the program in swift and confirm that this memory leak happens in fft function.
Will there be the method not to increase memory consumption on using fft function many times?

====
fft関数を使ってリアルタイムピッチ検出に使用しているのですが、関数のメモリ使用量で困っています。
fftを一秒に60回ほど行うのですが、関数実行のたびにメモリが数KBづつ消費され、あっというまにGB単位のメモリが使われてしまいます。

プログラムはswiftで書いていて、このメモリリークがfft関数内で起きていることも確認しています。
fft関数を多用するにあたり、メモリ消費量を増加させない方法はあるのでしょうか？

**Comment by mattt** [comment]
It looks like there was a missing call to `vDSP_destroy_fftsetup` causing `weights` to not be properly deallocated. This should be fixed by 3e8c754. Please let me know if you are still experiencing this.

**Comment by kiha-la** [comment]
I have not tried this method.
The memory leak is completely destroyed!
Thank you!
======
この方法はまだ試していませんでした。
メモリリークも完全になくなりました！
ありがとうございます！
