### ISSUE TITLE
Normalisation of magnitudes in FFT

### ISSUE THREAD

**Issue by nevosegal** [mattt/Surge#13]
Hi,

Just a question. Why are you scaling the magnitudes of the FFT by `2.0/Float(input.count)` ? What does this number represent?

Thanks!

**Comment by mattt** [comment]
`vDSP_zvmagsD` calculates the magnitude from the sum of squares of the real and imaginary components:

![vdsp_104](https://cloud.githubusercontent.com/assets/7659/7210864/9e47d2aa-e512-11e4-8dfe-ffa34cf68254.gif)

To normalize them, we take the square root and divide by two to account for the sum of both components being added together.

**Comment by nevosegal** [comment]
Thanks for the response! Hmmm maybe I'm missing something here but you're not dividing by two, you're multiplying by 2/input.count.. isn't that the case?

**Comment by mattt** [comment]
Apologies, I meant multiply, yes.

**Comment by nevosegal** [comment]
Thanks :1
