### ISSUE TITLE
How to read the results of "eigenDecompose"

### ISSUE THREAD

**Issue by chickweed01** [mattt/Surge#131]
Hello.

I am able to get results back from a call to `eigenDecompose` and view the components of `MatrixEigenDecompositionResult` using a `print` statement .

However, when I attempt to read the `eigenValues` in code using something like `ed.eigenValues` I get the following in XCode "'`eigenValues`' is inaccessible due to '`internal`' protection level".

How can I get the values in the `eigenValues` array? Thank you.

The Surge library is fantastic!

**Comment by regexident** [comment]
Hi @chickweed01, thanks for getting in touch!

It does indeed look to me like those should have been marked as `public`.
I have created a PR and pinged the initial contributor of said code: https://github.com/mattt/Surge/pull/132

**Comment by regexident** [comment]
Stay tuned for v2.3! 🙂

(Until then you might want to pin Surge to 8af8d180db90d3b8eb4289c4bc42b2d2f1878b4c, while developing.)
