### ISSUE TITLE
Use of unresolved identifier 'vDSP_create_fftsetup'

### ISSUE THREAD

**Issue by ephemer** [mattt/Surge#15]
Hi Mattt,

When compiling Surge for the iPad 2 simulator or other 32-bit processor simulators, we get a bunch of compile-time errors along the lines of `Use of unresolved identifier 'xyz'`, all Accelerate framework functions.

The problem is also described here: http://stackoverflow.com/questions/27114519/accessing-vdsp-from-swift-in-simulator-for-older-devices

Do you know of a workaround for this?

Thanks,
Geordie

**Comment by rfdickerson** [comment]
Can you let this know if this is still the case with Swift 3?

**Comment by aleph7** [comment]
Verified that this works on the latest Xcode.
