### ISSUE TITLE
Swift 2.0

### ISSUE THREAD

**Issue by ryanwmarsh** [mattt/Surge#16]
Any plans to upgrade to Swift 2.0?

**Comment by kostiakoval** [comment]
I need this one as well :) Probably will start working on it

**Comment by Boggartfly** [comment]
Yep this is needed, it seems there are a lot of syntax changes to the swift language. It is hell for anybody who just got the hang of the previous version and now has to re learn everything. Heck I got a Macbook Air just for learning Mac and iOS development! https://developer.apple.com/swift/blog/?id=29

**Comment by rfdickerson** [comment]
Swift 2.0 support has been merged in to the repository.
