### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by jhurliman** [mattt/Surge#18]
Surge is *almost* Carthage compatible. It looks like the only thing missing is marking the scheme for the Surge dynamic framework as "shared" in Xcode (then publishing a new release).

**Comment by aleph7** [comment]
My fork has Carthage support plus Swift 2.0: https://github.com/aleph7/Surge

**Comment by nacrossweb** [comment]
:+1:  I would like to see carthage support added.  The fork mentioned by @aleph7 doesn't seem to support tvos.

**Comment by rfdickerson** [comment]
I added a Cartfile to the project, but because we don't rely on any dependencies it remains empty. Let me know if this worked for you!
