### ISSUE TITLE
Swift 2 + Vectors?

### ISSUE THREAD

**Issue by innoreq** [mattt/Surge#23]
Hi Matt,

I'm just struggling with the need to perform matrix and vector operations in the context of associative matrices. Your Surge library seems to be pretty interesting (and usable!), however, it seems not yet to work on Swift 2. Do you plan a port in the near future?

Beside this, do you plan to enhance it with functions for matrix-vector functions, such as multiplying a matrix with a vector?

Best regards,
Hardy

**Comment by aleph7** [comment]
Mattt doesn't seem to be maintaining this project anymore. You can try my fork: https://github.com/aleph7/Surge

**Comment by rfdickerson** [comment]
The Surge project has just been updated to support Swift 2.
