### ISSUE TITLE
Public rows and columns properties

### ISSUE THREAD

**Issue by cloutiertyler** [mattt/Surge#32]
I am trying to create a Vector struct by wrapping the Matrix struct and asserting that the matrix is one dimensional. Thus I'd like to create a Vector constructor which constructs a Vector from a Matrix. However, the rows and columns Matrix properties are internal so I can't assert that columns is exactly 1. I've realized though that I can use Swift arrays to accomplish most vector operations but I think the point remains.

This is one use case in which I'd like to be able to access rows and columns from another module, but I can imagine others. Would it be possible to change make the rows and columns properties public? I can submit a pull request if you'd like.

**Comment by TheArtOfEngineering** [comment]
Access to the grid property is also important, as once you've got a Matrix, there is no way to convert it into anything else or get the data back out as an array.

**Comment by tdimeco** [comment]
I agree, could be very useful!

**Comment by aleph7** [comment]
Fixed.
