### ISSUE TITLE
Adding Travis CI

### ISSUE THREAD

**Issue by rfdickerson** [mattt/Surge#42]
In order to support a more stable library, we need a continuous integration system and a much more comprehensive set of tests.

**Comment by rfdickerson** [comment]
Hi Matt, when you get a chance can you add Surge to Travis CI?

https://travis-ci.org/mattt/Surge

**Comment by Boggartfly** [comment]
I would be happy to help! I'm currently using Jenkins my self, and I have hosted Jenkins on the cloud. Funny enough I have Jenkins on the cloud(Imagine that)!

**Comment by rfdickerson** [comment]
Hi @Boggartfly , I was just able to add support for Travis, but thanks for offering to help!

**Comment by Boggartfly** [comment]
Please do ping me if you need any sort of help with the project @rfdickerson ! Also I was wondering if you could have a look at my [project](https://github.com/Boggartfly/VUDX)? I need an extra set of eyes to sort out issues with the project. Maybe you could give me some guidance? Thanks!
