### ISSUE TITLE
EigenValue decomposition

### ISSUE THREAD

**Issue by carlobono** [mattt/Surge#49]
I thin the correct code at https://github.com/mattt/Surge/blob/matrix-eigendecomposition/Source/Matrix.swift : 255

should refer to &workspace rather than &workspaceQuery

is that correct?

C

**Comment by aleph7** [comment]
This seems to be obsolete, there is no such variable in the project.

**Comment by aleph7** [comment]
I didn't realized this refers to a branch.

**Comment by mattt** [comment]
Related to #14 and #55.

**Comment by alejandro-isaza** [comment]
Fixed in #95
