### ISSUE TITLE
initialization using array creates mismatch in grid size

### ISSUE THREAD

**Issue by loudinb** [mattt/Surge#57]
There seems to be an issue when initializing a matrix using an array.  The backing grid does not contain the correct number of elements (e.g. rows*columns) in all cases.

examples:
`Matrix([[1.0,2.0]])` results in a grid of [1.0, 2.0, 0.0] **// contains 1 extra element**
`Matrix([[1.0,2.0,3.0]])` results in a grid of [1.0, 2.0, 3.0, 0.0, 0.0] **// contains 2 extra elements**
`Matrix([[1.0,2.0],[1.0,2.0]])` results in a grid of [1.0, 2.0, 1.0, 2.0]
`Matrix([[1.0,2.0, 3.0],[1.0,2.0, 3.0]])` results in a grid of [1.0, 2.0, 3.0, 1.0, 2.0, 3.0, 0.0, 0.0]  **// contains 2 extra elements**

The problems seems to be caused by replaceSubrange.  There seems to be a problem in the calculation for the half open range:
`grid.replaceSubrange(i*n..<i*n+Swift.min(m, row.count), with: row)`

The problem seems to be fixed by moving to a closed range using the same range calculation.
`grid.replaceSubrange(i*n...i*n+Swift.min(m, row.count), with: row)`

**Comment by aleph7** [comment]
Fixed, thanks!
