### ISSUE TITLE
Importing Surge changes the behavior of + between array

### ISSUE THREAD

**Issue by tdimeco** [mattt/Surge#58]
Hi,

In files where Surge is imported, the behavior of the + operator between arrays is modified by the library.

Normal Swift behavior : concatenation
```swift
[1.0, 2.0, 3.0] + [1.0, 2.0, 3.0] // [1.0, 2.0, 3.0, 4.0, 5.0, 6.0]
```

Surge overloaded behavior : addition
```swift
[1.0, 2.0, 3.0] + [1.0, 2.0, 3.0] // [2.0, 4.0, 6.0]
```

I don't know if it's a feature or a bug, but it took me 2 hours to find the problem after importing Surge into my code. So maybe it's a bad idea to overload this operator.

What do you think about removing this feature?

**Comment by morpheby** [comment]
What about using ".+"-style for all element-wise operations?

**Comment by alejandro-isaza** [comment]
That's a good idea @morpheby can you make a PR with that change?
