### ISSUE TITLE
Missing sub method for Matrix

### ISSUE THREAD

**Issue by tdimeco** [mattt/Surge#59]
Hi,

I realized there is no methods to substract two matrix. Maybe it's related to Accelerate, that does not provide any method to substract matrix?

Maybe it makes sense to add a sub method and a - operator for matrix, that do something like : 

```swift
add(lhs, mul(-1.0, rhs))
```

What do you think about this?

**Comment by remzr7** [comment]
I added a sub method in this fork  https://github.com/remzr7/Surge

**Comment by plm75** [comment]
It would be nice if that was added directly here or if @remzr7 could make a pull request maybe ?

**Comment by aleph7** [comment]
It's in
