### ISSUE TITLE
New release for Swift 3

### ISSUE THREAD

**Issue by stsievert** [mattt/Surge#60]
I'm using Surge for a project, and I'm getting complaints about Surge not having Swift 3 syntax. It'd be nice to make a new tag since master branch supports it.

**Comment by stsievert** [comment]
I'd hold off on tagging a release; I still have to put in a PR to format for new swift changes (renaming Source => Sources, moving tests inside module).

**Comment by remzr7** [comment]
I made another branch with Swift 3 PM compatibility https://github.com/remzr7/Surge 

Doesn't seem like the owners care about the repo anymore

**Comment by dmr07** [comment]
@remzr7 I integrated your code base and ran into a compile error. I read over the docs on Sequences and Iterators in Swift, but I'm still not sure how to fix this. I was wondering if you can help.

Error:
`'Sequence' requires the types 'T' and 'ArraySlice<T>' be equivalent`

```
extension Matrix: Sequence { // <-- error occurs here
    public func makeIterator() -> AnyIterator<ArraySlice<Element>> {
        let endIndex = rows * columns
        var nextRowStartIndex = 0
        
        return AnyIterator {
            if nextRowStartIndex == endIndex {
                return nil
            }
            
            let currentRowStartIndex = nextRowStartIndex
            nextRowStartIndex += self.columns
            
            return self.grid[currentRowStartIndex..<nextRowStartIndex]
        }
    }
}
```

**Comment by aleph7** [comment]
Swift 3.2 supported in 2.0.0
