### ISSUE TITLE
How to get matrix values?

### ISSUE THREAD

**Issue by Patrickyp** [mattt/Surge#64]
I downloaded the framework and included in my xcode project and it seems to be working fine. However, I would like to access the matrix elements and I don't know how.  Can someone help me?

```
//create arbitrary matrix, this works fine
var matrix : Matrix<Double> = Matrix<Double>([[4,7], [2,6]])

// I want to get the 4 but this doesn't work..
let rm11 = resultMatrix.subscript(row:1,col:1)
```

**Comment by NobodyNada** [comment]
http://stackoverflow.com/questions/43814415/how-to-get-matrix-values-using-surge

**Comment by aleph7** [comment]
Seems to be resolved in the link.
