### ISSUE TITLE
This project is abandoned?

### ISSUE THREAD

**Issue by MKGitHub** [mattt/Surge#69]
This project is abandoned?

**Comment by Narsail** [comment]
It seems so. [Upsurge](https://github.com/aleph7/Upsurge) seems to be a nice alternative.

**Comment by dmr07** [comment]
Upsurge is probably the better choice; I've also forked this project and made it Swift3.0+ compatible. https://github.com/dmr07/Surge4Swift3Plus. You can included in your podfile with `pod Surge4Swift3Plus`

**Comment by aleph7** [comment]
Not anymore! @mattt graciously invited me to maintain Surge. I also maintain Upsurge so great opportunity to pull on the same direction.

**Comment by Narsail** [comment]
Why not merging both projects? Btw when will you release a Swift 4 Version of Upsurge? :)

**Comment by aleph7** [comment]
Upsurge has some interesting ideas but is more focused towards Tensors. I think eventually it will depend on Surge or some core framework and just add to it. I'll work on Swift 4 soon but I want to first do a pass on the API to make it more Swift-y and release that as version 3.0.
