### ISSUE TITLE
Sequence' requires the types 'T' and 'ArraySlice<T>' be equivalent

### ISSUE THREAD

**Issue by SosonHuang** [mattt/Surge#72]
in Xcode 9，A compiler error：

Sequence' requires the types 'T' and 'ArraySlice<T>' be equivalent

**Comment by aleph7** [comment]
What exact version of Xcode are you using? Where (file, line number) is this error being reported?

**Comment by SosonHuang** [comment]
![image](https://user-images.githubusercontent.com/6091199/31649507-d9569642-b2d8-11e7-8f31-f5f8e7ef7577.png)

**Comment by aleph7** [comment]
Are you on `master`?

**Comment by SosonHuang** [comment]
I'm not

**Comment by aleph7** [comment]
That problem is fixed on master, please use that.

**Comment by SosonHuang** [comment]
thank you！
