### ISSUE TITLE
Dot product operator has DefaultPrecedence

### ISSUE THREAD

**Issue by morpheby** [mattt/Surge#79]
Operator `•` (dot product) is defined without precedence group, which by default assigns it to DefaultPrecedence group.

Per Swift docs, 

> DefaultPrecedence has no associativity and a precedence immediately higher than TernaryPrecedence

Probably it should be reasonable to have MultiplicationPrecedence for the dot product. Right now,  such operations as `5.0 + b • c` result in error `Adjacent operators are in unordered precedence groups 'AdditionPrecedence' and 'DefaultPrecedence'`.

Setting `operator •` to MultiplicationPrecedence removes this error.

**Comment by alejandro-isaza** [comment]
Can you create a PR please?

**Comment by mattt** [comment]
This is now fixed as of 245bd8f. See https://github.com/mattt/Surge/blob/master/Sources/Surge/Arithmetic.swift#L518.
