### ISSUE TITLE
enhancement - helpers to instantiate matrix / apply valueFunc  

### ISSUE THREAD

**Issue by johndpope** [mattt/Surge#85]
https://github.com/dyashkir/Surge/commit/3e45f0255f193797bf5665f2d8f422a59f3d16ac

I'm digging through some old (2 yrs) repo by @dyashkir - and it's using a bespoke fork of Surge

it includes an initialization of a matrix by passing a valueFunc into it.

 self.weightsInputToHidden = Matrix(rows: nodeCountHidden, columns: nodeCountInput, valueFunc: { return (drand48() - 0.5)

Is this kind of thing possible without do this? if so how? otherwise - would you please consider adding to this library? in mean time - I'll try to bring the old library up to date.

Thanks in advance

**Comment by johndpope** [comment]
the initial setting maybe straight forward - but this looks nifty for apply across matrix.   

     let hiddenInputs = Surge.mul(self.weightsInputToHidden, inp)
        **let hiddenOutputs = Surge.apply(hiddenInputs, function: activation)**

**Comment by mattt** [comment]
I like the idea of being able to set the values of a Matrix using a function type during initialization. Thanks for the suggestion, @johndpope!

I think this design could be improved by having the passed function accept arguments for the row and column:

```swift
init(rows: Int, columns: Int, settingValuesForPositions f: (row: Int, column: Int) rethrows -> Element) rethrows
```

`settingValuesForPositions` and `f` are strawman names; please bikeshed this. Also, I think such a function should be able to `throw`, which means makes initializer itself `rethrows`.

**Comment by johndpope** [comment]
Been digging around github to get some swift code to run neural nets with Surge - found this other repo by @wpc with these helpers - specifically - vDSP_maxvi 
adding here to this enhancement ticket 

Arithmetic.swift

```swift
public func maxi(x: [Float]) -> Int {
    var max: Float = 0.0
    var index: vDSP_Length = vDSP_Length(0)
    vDSP_maxvi(x, 1, &max, &index, vDSP_Length(x.count))
     return Int(index)
}
 public func maxi(x: [Double]) -> Int {
    var max: Double = 0.0
    var index: vDSP_Length = vDSP_Length(0)
    vDSP_maxviD(x, 1, &max, &index, vDSP_Length(x.count))
    return Int(index)
}

```
 https://github.com/wpc/Surge/commit/dd61e5263b5877d49bec97917627f989839d5b64
Would be nice to consolidate efforts around neural nets with Surge. 

thus far 
https://github.com/morpheby/Seconn-Swift
https://github.com/wpc/NeuralNet (swift2)
https://github.com/dyashkir/neuralnetapp

**Comment by johndpope** [comment]
@mattt  - found this treasure trove of matrix helpers
https://github.com/sonsongithub/numsw/tree/master/Sources/numsw/Matrix

specifically - 
```swift
infix operator .*
infix operator .*=

func apply<T, R>(_ arg: Matrix<T>, _ handler: (T) -> R) -> Matrix<R> {
    return Matrix(rows: arg.rows,
                  columns: arg.columns,
                  elements: apply(arg.elements, handler))
}

func combine<T, U, R>(_ lhs: Matrix<T>, _ rhs: Matrix<U>, _ handler: (T, U) -> R) -> Matrix<R> {
    precondition(lhs.rows==rhs.rows && lhs.columns == rhs.columns, "Two matrices have incompatible shape.")
    
    return Matrix(rows: lhs.rows,
                  columns: lhs.columns,
                  elements: combine(lhs.elements, rhs.elements, handler))
}

```
https://github.com/sonsongithub/numsw/blob/master/Sources/numsw/Matrix/MatrixUtils.swift

**Comment by johndpope** [comment]
thanks @regexident - doing a spring clean on github issues and going to close this.
