### ISSUE TITLE
 (2.1.0) Cannot invoke 'dist' with an argument list of type '([Float], y: [Float])'

### ISSUE THREAD

**Issue by yourleaves** [mattt/Surge#86]
Now I use at 2.1.0  Cannot invoke 'dist' with an argument list of type '([Float], y: [Float])' why?

**Comment by alejandro-isaza** [comment]
try removing the `y:` label: `dist(a, b)`

**Comment by mattt** [comment]
Hi @yourleaves. @alejandro-isaza is correct. If you look at the [method signature](https://github.com/mattt/Surge/blob/245bd8faebf1bb9bb775b2701e3a15aa7051d3f3/Sources/Surge/Arithmetic.swift#L261-L269), the `x` and `y` parameters begin with an underscore, so they don't have labels:

```swift
public func dist<X: UnsafeMemoryAccessible, Y: UnsafeMemoryAccessible>(_ x: X, _ y: Y) -> Float where X.Element == Float, Y.Element == Float { ... }
```

This is a change from previous versions, where fluctuations in Swift argument syntax caused labels to appear and disappear between releases.

Here's some example code that should work with the latest version:

```swift
import Surge

let a = [1.0, 3.0, 5.0, 7.0]
let b = [2.0, 4.0, 6.0, 8.0]
dist(a, b) // 2
```
