### ISSUE TITLE
Can't run Surge as Command Line Tool

### ISSUE THREAD

**Issue by nnorris7** [mattt/Surge#90]
I am able to get Surge to work as an iOS app and a Cocoa app but am unable to get it to work as a Command Line Tool. I followed all the same procedures as I did for the other apps but when I run the CLT, it (runtime) crashes with the following error:

> dyld: Library not loaded: @rpath/libswiftAccelerate.dylib
  Referenced from: /Users/norm/Library/Developer/Xcode/DerivedData/Surge_CLI-enrdshevubvulcaiimedbqrgxfrw/Build/Products/Debug/Surge.framework/Versions/A/Surge
  Reason: image not found

I added the Accelerate.framework under Link Binary with Libraries but that did not solve the problem.

I was wondering if there was some workaround to get Surge working in a CLT.

**Comment by mattt** [comment]
@nnorris7 Thanks for pointing that out. I've been meaning to revisit and expand the benchmarks to ensure that they're accurate and up-to-date.
