### ISSUE TITLE
Hard crash when multiplying by empty matrix (process exits -1)

### ISSUE THREAD

**Issue by jdanbrown** [mattt/Surge#92]
```swift
import Surge

let X = Matrix<Float>([[1]])
let Y = Matrix<Float>([[]])

print("X")
print(X) // Ok
print("Y")
print(Y) // Ok
print("X*Y")
print(X*Y) // Hard crash
```

Output:
```
X
(       1.0     )

Y
(               )

X*Y
ldb must be >= MAX(N,1): ldb=0 N=0ldc must be >= MAX(N,1): ldc=0 N=0BLAS error: Parameter number 11 passed to cblas_sgemm had an invalid value
```

When run like `swift <script>.swift`, process prints that error msg and exits -1 (= 255), without printing a stacktrace. When run in Xcode, debugger doesn't activate.

Seems like Surge `mul()` needs to guard against the rows=0 / columns=0 cases and return an appropriate empty Matrix, instead of letting blas crash?

**Comment by alejandro-isaza** [comment]
Added a precondition check.

**Comment by jdanbrown** [comment]
Thanks! But what do you think about returning an empty matrix instead of treating it as an error? That seems less surprising mathematically, since empty matrices are valid objects. That's what e.g. numpy chooses to do:
```py
>>> M = lambda r, c: np.random.rand(r, c)

>>> np.dot(M(1,2), M(2,0))
array([], shape=(1, 0), dtype=float64)

>>> np.dot(M(0,2), M(2,3))
array([], shape=(0, 3), dtype=float64)

>>> np.dot(M(1,0), M(0,3))
array([[0., 0., 0.]])
```

**Comment by alejandro-isaza** [comment]
Interesting, what about this: https://github.com/mattt/Surge/pull/93
